version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
  
  app2: 
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - "4000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
  
