pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                echo 'Building the application'

            }
        }
        
        stage('Test') {
            steps {
                echo 'Testing the application'

            }
        }
        
        stage('Run') {
            steps {
                echo 'Running the application'

                sh 'npm start'
            }
        }
    }
    
    post {
        always {

        }
    }
}
